using System.Collections.Generic;
using Abp.Rest.Orders;

namespace Abp.Rest.Seeders
{
    public static class ClientsData
    {
        public static IEnumerable<Client> GetData()
        {
            return new[]
            {
                new Client {FullName = "João da Silva"},
                new Client {FullName = "Mr. Rigoberto D'Amore"},
                new Client {FullName = "Ray Deckow"},
                new Client {FullName = "Johnathan Armstrong"},
                new Client {FullName = "Savion Kirlin"},
                new Client {FullName = "Laurel Bernier"},
                new Client {FullName = "Stephania Heaney"},
                new Client {FullName = "Prof. Hassan Jast Jr."},
                new Client {FullName = "Mr. Greg Stiedemann DVM"},
                new Client {FullName = "Prof. Milford Ortiz"},
                new Client {FullName = "Dr. Hans Chucrute"},
                new Client {FullName = "Meagan Ernser"},
                new Client {FullName = "Neha Denesik III"},
                new Client {FullName = "Giovani Hills"},
                new Client {FullName = "Mrs. Reba Feeney I"},
                new Client {FullName = "Prof. Tyrel Corkery MD"},
                new Client {FullName = "Prof. Mckayla Heidenreich MD"},
                new Client {FullName = "Melvin Becker"},
                new Client {FullName = "Lilly Auer"},
                new Client {FullName = "Woodrow Macejkovic"},
                new Client {FullName = "Eva Nolan"},
                new Client {FullName = "Alberta Rippin"},
                new Client {FullName = "Ophelia Zboncak"},
                new Client {FullName = "Prof. Brandon Wilkinson"},
                new Client {FullName = "Dr. Lance Beer DDS"},
                new Client {FullName = "Tia Gorczany V"},
                new Client {FullName = "Miss Lenna Littel"},
                new Client {FullName = "Prof. Marco Cummerata DDS"},
                new Client {FullName = "Miss Brenna Trantow MD"},
                new Client {FullName = "Mr. Brooks Hickle DDS"},
                new Client {FullName = "Nakia Raynor"},
                new Client {FullName = "Stella Mante"},
                new Client {FullName = "Dr. Napoleon Sipes IV"},
                new Client {FullName = "Mrs. Carissa Champlin I"},
                new Client {FullName = "Dr. Eudora Cronin Sr."},
                new Client {FullName = "Miguel Block"},
                new Client {FullName = "Keanu Stark DVM"},
                new Client {FullName = "Cassidy Heidenreich"},
                new Client {FullName = "Kaia Trantow"},
                new Client {FullName = "Roxane Volkman"},
                new Client {FullName = "Felipe Gislason III"},
                new Client {FullName = "Tressa Von"},
                new Client {FullName = "Prof. Eleazar Walker DDS"},
                new Client {FullName = "Ned Von"},
                new Client {FullName = "Haley Lubowitz"},
                new Client {FullName = "Prof. Katrina Bartoletti PhD"},
                new Client {FullName = "Wayne Altenwerth"},
                new Client {FullName = "Lazaro Frami"},
                new Client {FullName = "Mr. Lonzo Mraz PhD"},
                new Client {FullName = "Ludie Gutkowski"},
                new Client {FullName = "Dr. Ewald Schowalter V"},
                new Client {FullName = "Mr. Jerel Ankunding"},
                new Client {FullName = "Patience Gerhold"},
                new Client {FullName = "Rachael Becker III"},
                new Client {FullName = "Ms. Brielle Kuhn"},
                new Client {FullName = "Philip Becker"},
                new Client {FullName = "Brianne Bosco"},
                new Client {FullName = "Prof. Anthony Collier"},
                new Client {FullName = "Dr. Candice Marks I"},
                new Client {FullName = "Estella Ryan"},
                new Client {FullName = "Dr. Shaniya Keeling"},
                new Client {FullName = "Jordane Abernathy Sr."},
                new Client {FullName = "Garfield Grimes"},
                new Client {FullName = "General Mraz"},
                new Client {FullName = "Sienna Medhurst V"},
                new Client {FullName = "Ed McDermott"},
                new Client {FullName = "Vern Ledner"},
                new Client {FullName = "Daryl Dickinson"},
                new Client {FullName = "Leonard Kerluke"},
                new Client {FullName = "Ed Stamm"},
                new Client {FullName = "Myra O'Hara"},
                new Client {FullName = "Ms. Telly Olson"},
                new Client {FullName = "Elva Thiel DVM"},
                new Client {FullName = "Miss Fleta Smith DDS"},
                new Client {FullName = "Mr. Jasen Wunsch"},
                new Client {FullName = "Ms. Rosalind Ryan"},
                new Client {FullName = "Ole Walker"},
                new Client {FullName = "Albina Marquardt"},
                new Client {FullName = "Nicola Pollich MD"},
                new Client {FullName = "Dr. Elbert Leffler III"},
                new Client {FullName = "Waylon Hermann"},
                new Client {FullName = "Antonetta Conroy"},
                new Client {FullName = "Prof. Beryl Kunde V"},
                new Client {FullName = "Dr. Patrick Denesik III"},
                new Client {FullName = "Carol Kulas"},
                new Client {FullName = "Deon Kassulk"},
                new Client {FullName = "Dorthy Nitzsche"},
                new Client {FullName = "Valentine Runolfsson"},
                new Client {FullName = "Dannie Howe II"},
                new Client {FullName = "Jenifer Schuster"},
                new Client {FullName = "Kali Jacobi"},
                new Client {FullName = "Dr. Talon Ward II"},
                new Client {FullName = "Robert Weber Sr."},
                new Client {FullName = "Angela Schuppe"},
                new Client {FullName = "Rogers Schmidt"},
                new Client {FullName = "Kim Murray I"},
                new Client {FullName = "Prof. Bennett Keeling III"},
                new Client {FullName = "Foster VonRueden"},
                new Client {FullName = "Eda Gusikowski"},
                new Client {FullName = "Prof. Friedrich Brakus"}
            };
        }
    }
}